applicationsets:
  microservices:
    goTemplate: true
    goTemplateOptions:
      - missingkey=error
    generators:
      - git:
          repoURL: https://github.com/kvncont/ms-control-plane.git
          revision: main
          files:
            - path: environments/dev/app-*.yml
            - path: environments/dev/app-*.yaml
    template:
      metadata:
        name: "{{.fullnameOverride}}"
      spec:
        project: backends
        source:
          repoURL: https://github.com/kvncont/ms-control-plane.git
          targetRevision: main
          path: environments/dev/
        destination:
          server: ${cluster_server}
          namespace: default
        syncPolicy:
          automated:
            prune: false
            selfHeal: false
          syncOptions:
            - CreateNamespace=true
